name: CI Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lgbt-game
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -u root -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Wait for MySQL
        run: |
          sudo apt-get install -y mysql-client
          while ! mysqladmin ping -h"127.0.0.1" -u"testuser" -p"testpass" --silent; do
            sleep 1
          done

      - name: Run backend tests
        env:
          DB_DEV_USERNAME: testuser
          DB_DEV_PASSWORD: testpass
          JWT_SECRET: testsecret
          SPRING_PROFILES_ACTIVE: dev
        run: |
          cd Backend
          mvn clean test

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm ci

      - name: Run frontend linting
        run: |
          cd Frontend
          npm run lint

      - name: Build frontend
        run: |
          cd Frontend
          npm run build