name: CI Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - run: |
          cd Backend
          rm -rf src/main/resources/db
          mvn test -Dtest=AuthControllerTest
          mvn test -Dtest=GameHistoryControllerTest
          mvn test -Dtest=StatementControllerTest
          mvn test -Dtest=UserControllerTest
          mvn test -Dtest=GameHistoryServiceImplTest
          mvn test -Dtest=StatementServiceImplTest
          mvn test -Dtest=UserServiceImplTest
        env:
          DB_DEV_STRING: ${{ secrets.DB_DEV_STRING }}
          DB_DEV_USERNAME: ${{ secrets.DB_DEV_USERNAME }}
          DB_DEV_PASSWORD: ${{ secrets.DB_DEV_PASSWORD }}
          DB_DEV_DRIVER: ${{ secrets.DB_DEV_DRIVER }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}

  frontend-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm i

      - name: Run frontend linting
        run: |
          cd Frontend
          npm run lint

      - name: Build frontend
        run: |
          cd Frontend
          npm run build