name: CI Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  backend-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lgbt-game
          MYSQL_USER: testuser
          MYSQL_PASSWORD: testpass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -uroot -proot"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DB_URL: jdbc:mysql://localhost:3306/lgbt-game?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      DB_USER: testuser
      DB_PASSWORD: testpass
      SPRING_PROFILES_ACTIVE: test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Wait for MySQL
        run: |
          for i in {1..30}; do
            if mysqladmin ping -h"127.0.0.1" -uroot -proot --silent; then
              echo "MySQL is ready"
              break
            fi
            echo "Waiting for MySQL to start... (attempt $i)"
            sleep 2
          done
          # Configura usuário de teste
          mysql -h 127.0.0.1 -uroot -proot -e "CREATE USER IF NOT EXISTS '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';"
          mysql -h 127.0.0.1 -uroot -proot -e "GRANT ALL PRIVILEGES ON \`lgbt-game\`.* TO '$DB_USER'@'%';"
          mysql -h 127.0.0.1 -uroot -proot -e "FLUSH PRIVILEGES;"

      - name: Configure test properties
        run: |
          cd Backend
          echo "spring.datasource.url=$DB_URL" > src/test/resources/application-test.properties
          echo "spring.datasource.username=$DB_USER" >> src/test/resources/application-test.properties
          echo "spring.datasource.password=$DB_PASSWORD" >> src/test/resources/application-test.properties
          echo "spring.flyway.url=$DB_URL" >> src/test/resources/application-test.properties
          echo "spring.flyway.user=$DB_USER" >> src/test/resources/application-test.properties
          echo "spring.flyway.password=$DB_PASSWORD" >> src/test/resources/application-test.properties
          echo "spring.flyway.clean-disabled=false" >> src/test/resources/application-test.properties
          echo "spring.flyway.repair-on-migrate=true" >> src/test/resources/application-test.properties

      - name: Run tests
        run: |
          cd Backend
          mvn clean test -Dspring.profiles.active=test
          # Mostra logs em caso de falha
          cat target/surefire-reports/*.txt || true

  frontend-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: Frontend/package-lock.json

      - name: Install frontend dependencies
        run: |
          cd Frontend
          npm ci

      - name: Run frontend linting
        run: |
          cd Frontend
          npm run lint

      - name: Build frontend
        run: |
          cd Frontend
          npm run build